GooeyAI/gooey-server

daras_ai_v2/doc_search_settings_widgets.py
daras_ai_v2/language_model.py
daras_ai_v2/language_model_settings_widgets.py
recipes/BulkEval.py
recipes/CompareLLM.py
recipes/DocExtract.py
recipes/DocSearch.py
recipes/DocSummary.py
recipes/GoogleGPT.py
recipes/SEOSummary.py
recipes/SmartGPT.py
recipes/SocialLookupEmail.py
recipes/VideoBots.py

Task: https://app.asana.com/0/1203067047205953/1207720614246546
Only for gpt4o, gpt4 turbo vision, and gpt4 turbo
```bash
```
```bash
```
```bash
```
```bash
```
```python
import pandas …
```

Json format on doc_search, doc_summary, and google_gpt

---

bots/models.py
recipes/VideoBotsStats.py

Task: https://app.asana.com/0/1203067047205953/1207501137630904
```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

Stats bug prevention

---

celeryapp/tasks.py
daras_ai_v2/base.py
daras_ai_v2/text_to_speech_settings_widgets.py
recipes/TextToSpeech.py
recipes/VideoBots.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

Fix TTS to work with user-owned elevenlabs API key

---

daras_ai_v2/base.py
gooey_ui/components/__init__.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

truncate related workflows description text

---

daras_ai_v2/asr.py
recipes/VideoBots.py

Task: https://app.asana.com/0/1203067047205953/1204911106314540
```bash
```
```bash
```
```bash
```
```bash
```
```python
...
```

New seamless version!

---

bots/admin.py
bots/models.py
celeryapp/tasks.py
daras_ai_v2/base.py
daras_ai_v2/safety_checker.py
functions/recipe_functions.py
recipes/Functions.py
routers/api.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

functions:  charge 1 credit in /functions and no credit from another workflow

---

routers/static_pages.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

Add no cache header for downloads from GCS

---

daras_ai_v2/base.py
daras_ai_v2/prompt_vars.py
recipes/VideoBots.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

run before save - if unsaved changes in current run

---

routers/root.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix integrations tab ui jump

---

bots/admin.py
bots/models.py
bots/tasks.py
celeryapp/tasks.py
conftest.py
daras_ai_v2/base.py
daras_ai_v2/bot_integration_widgets.py
daras_ai_v2/bots.py
daras_ai_v2/doc_search_settings_widgets.py
daras_ai_v2/meta_content.py
daras_ai_v2/safety_checker.py
daras_ai_v2/workflow_url_input.py
explore.py
functions/recipe_functions.py
recipes/BulkRunner.py
recipes/DocSearch.py
recipes/Functions.py
recipes/GoogleGPT.py
recipes/LipsyncTTS.py
recipes/VideoBots.py
recipes/VideoBotsStats.py
recipes/asr_page.py
routers/api.py
routers/bots_api.py
routers/root.py
routers/twilio_api.py
tests/test_apis.py
tests/test_pricing.py
url_shortener/models.py
usage_costs/cost_utils.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

Refactor `BasePage` methods to consolidate `SavedRun` and `PublishedRun` retrieval logic into `get_sr_pr` + caching

---

daras_ai_v2/serp_search_locations.py

Looks like an accidental typo when a global s/st/gui was done
```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix SERP search location code gui->st

---

daras_ai_v2/asr.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

Ghana NLP ASR v2

---

daras_ai_v2/asr.py
recipes/asr_page.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fetch ghana translation target languages from api

---

recipes/BulkEval.py

- Add default for Eval language model and add settings
- Hide LM settings on eval because they are being ignored
- fix type of passed selected_model to submit in Eval
```bash
```
```bash
```
```bash
```
```bash
```
To reduce import times, import libraries that take a long time inside the functions that use them instead of at the top of …

fix: pass LargeLanguageModels to submit(), not str

---

recipes/VideoBots.py
routers/root.py
templates/footer.html

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

Fix Whatsapp text Integration text & Footer year text

---

daras_ai_v2/base.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix save flow for anon users

---

daras_ai_v2/asr.py
daras_ai_v2/vector_search.py
recipes/DocExtract.py
tests/test_yt_dlp.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

support facebook video url download via yt-dlp

---

daras_ai_v2/base.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix: run is queued with stale uid

---

daras_ai_v2/base.py
recipes/VideoBotsStats.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

Fix social buttons bug on video bots stats page

---

scripts/deployment/vespa.captain-definition

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix syntax error in vespa.captain-definition

---

Dockerfile

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix #495: add new link for libssl.deb in dockerfile

---

bots/admin.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix bot-integrations admin search: created_by__name->created_by__display_name

---

daras_ai_v2/billing.py
routers/account.py

TODO: display workspace on billing tab. waiting on workspace-breadcrumbs merge for that.
```bash
```
```bash
```
```bash
```
```bash
```
```python
...
```
Look, I …

update text on account->saved tab

---

app_users/admin.py
bots/admin.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

add fk fields to autocomplete_fields - use select2

---

daras_ai_v2/base.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix bug where 'Share' modal disappears when form input changes

---

daras_ai_v2/base.py
daras_ai_v2/breadcrumbs.py
daras_ai_v2/icons.py

- **fix alignment in header on workflow pages**
- **add text-nowrap on "unpublished changes" indicator**
- **fix bug where 'Share' modal disappears when form input changes**
- **hide text on 'share' button on smaller screens**
- **fix: make title occupy full-width under breadcrumbs+buttons row**
```bash
```
```bash
```
```bash
```
```bash
sys time    0.72 secs  613.00 micros    0.72 …
```

fix header on workflow pages: breadcrumb alignment, title, and responsive share buton

---

daras_ai_v2/base.py

accidentally reverted in master by merging a branch that reverted this change for separation of concerns.
```bash
```
```bash
```
```bash
```
```bash
```
```python …
```

re-fix: bug where share modal disappears when input form changes

---

poetry.lock
pyproject.toml
recipes/DeforumSD.py

Asana: https://app.asana.com/0/1203067047205953/1205632871208949
I made a new pr since the old one was very outdated. I did implement the feedback Dev provided in the previous pr.
```bash
```
```bash
```
```bash
```
```bash
```
To reduce import times, import libraries that take a long time inside the functions that use them instead of …

Latest update deforum ux

---

daras_ai_v2/base.py
daras_ai_v2/copy_to_clipboard_button_widget.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix copy-link button behaviour in share dialog

---

daras_ai_v2/settings.py

- **add security settings for django admin dashboard**
- **add HSTS for django admin**
```bash
```
```bash
```
```bash
```
```bash
```
```python
...
```
Look, I get …

Add HSTS configuration (disabled by default)

---

workspaces/models.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

auto-accept workspace invitation for all existing AppUsers. Otherwise send email

---

daras_ai_v2/language_model.py
scripts/init_llm_pricing.py

3.2 90B + Vision
3.2 11B + Vision
3.2 3B
3.2 1B
3.1 70B
3.1 8B
```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

add new llama models

---

recipes/CompareLLM.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix: /llm - NoneType has no '.items()'

---

recipes/Lipsync.py
recipes/LipsyncTTS.py
recipes/VideoBots.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

change description for lipsync on /copilot, /lipsync and /lipsynctts

---

daras_ai_v2/upscaler_models.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix link in comment to replicate model for gfpgan

---

bots/models.py
daras_ai_v2/base.py

- **fix visibility: dont change to unlisted on 'Save'**
- **fix: default visibility for new published runs**
```bash
```
```bash
```
```bash
```
```bash
```
```python
import pandas as …
```

fix unlisted visibility on save

---

templates/auto_added_to_workspace_email.html

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

Only show line about workspace domain in "Welcome to {workspace}" email if user domain matches

---

daras_ai_v2/asr.py
daras_ai_v2/language_model.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

rename _run_openai_chat->run_openai_chat, fix usage in asr.py

---

routers/root.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix next URL on tapping 'Sign In' - should include query params

---

daras_ai_v2/gdrive_downloader.py
daras_ai_v2/glossary.py
daras_ai_v2/office_utils_pptx.py
daras_ai_v2/vector_search.py
files/models.py
recipes/BulkRunner.py
recipes/DocExtract.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix: pptx uploaded on google docs 

---

daras_ai_v2/gdrive_downloader.py
daras_ai_v2/vector_search.py
files/models.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

support all non exportable google workspace docs

---

daras_ai_v2/language_model.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

use max_completion_tokens for o1 models, and max_tokens for the rest

---

daras_ai_v2/vector_search.py
poetry.lock
pyproject.toml

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

add xls support

---

daras_ai_v2/vector_search.py
files/models.py
recipes/DocExtract.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

add default cache_knowledge to google bucket urls

---

daras_ai_v2/doc_search_settings_widgets.py
daras_ai_v2/vector_search.py
recipes/VideoBots.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

add cache knowledge checkbox

---

celeryapp/tasks.py
daras_ai_v2/base.py
daras_ai_v2/doc_search_settings_widgets.py
recipes/DocSearch.py
recipes/GoogleGPT.py
recipes/VideoBots.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

refactor ux to doc_search_settings_widgets

---

daras_ai_v2/base.py
daras_ai_v2/breadcrumbs.py
daras_ai_v2/variables_widget.py
poetry.lock
pyproject.toml
workspaces/admin.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

replace inline styles with gui.styled()

---

daras_ai_v2/base.py
daras_ai_v2/utils.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

show last saved time

---

daras_ai_v2/profiles.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

chagne clear cover button to secondary variant

---

bots/models.py
daras_ai_v2/base.py

selectively enables showing "Public" visibility for public examples
```bash
```
```bash
```
```bash
```
```bash
```
```python
...
```
Look, I get it. The entity …

show "Public" visibility for already public published runs in team workspace

---

daras_ai_v2/language_model.py

both are not supported by the o1 API at this point
```bash
```
```bash
```
```bash
```
```bash
```
```python
...
```
Look, I get it. The entity doing business as …

fix o1 API call: ignore avoid_repetition and response_format_type options

---

daras_ai_v2/bots.py
daras_ai_v2/csv_lines.py
daras_ai_v2/facebook_bots.py
routers/bots_api.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

support LLM generated html buttons in whatsapp and web api

---

daras_ai_v2/base.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

show last ran time instead of updated_at always

---

workspaces/widgets.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix redirects for team workspaces: billing/members to saved

---

recipes/VideoBots.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

update whatsapp intergration decription text

---

daras_ai_v2/onedrive_downloader.py
routers/onedrive_api.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

Added support for SharePoint-based OneDrive URLs

---

routers/onedrive_api.py
templates/authorization_error.html

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

Add onedrive/sharepoint authorization error template

---

daras_ai_v2/language_model.py
daras_ai_v2/language_model_settings_widgets.py
recipes/CompareLLM.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix: set upper bound on max_tokens parameter for LLMs

---

workspaces/models.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix: TypeError in WorkspaceInvite.has_expired because updated_at is None before db insert

---

daras_ai_v2/base.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix: default to current_workspace in publish_dialog for non-editors

---

recipes/CompareText2Img.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

Update preview_image in `CompareText2Img.py`

---

daras_ai_v2/bot_integration_widgets.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

remove `%text=hi` from whatsapp links

---

daras_ai_v2/language_model.py
scripts/init_llm_pricing.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

add LLMs: gemini 2.5 pro, gemini 2 flash lite, llama4 maverick, llama4 scout

---

daras_ai_v2/language_model.py

- avoid validation error
```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

o1 o3mini validation error - Add "developer" role to ConversationEntry type

---

recipes/ModelTrainer.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix contextmanager import: import from contextlib instead of blib2to3.gen2.parse

---

app_users/models.py
bots/models.py
poetry.lock
pyproject.toml
widgets/workflow_search.py
workspaces/models.py

for /api/ pages where we use it for formatting the code examples.
this wasn't caught by CI tests because the image comes with the
black package by default.
```bash
```
```bash
```
```bash
```
```bash
``` …

fix: add black to dependency-list for formatting API example code

---

widgets/workflow_share.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix: clicking share button throws internal error for site admin

---

daras_ai_v2/base.py
daras_ai_v2/icons.py
widgets/base_header.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

show "Help Guide" button on root workflows

---

daras_ai_v2/base.py
widgets/workflow_image.py
widgets/workflow_metadata_gen.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

make copilot workflow image to rounded-circle border

---

daras_ai_v2/facebook_bots.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

add typing indicator functionality for WhatsApp bot

---

widgets/saved_workflow.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix: flex overflow in render_author_run_count row

---

recipes/BulkRunner.py

Resetting the index after dropping rows ensures consistent indexing, which prevents KeyError issues when processing CSV files with empty rows in between.
```bash
```
```bash
```
```bash
```
```bash
``` …

fix: reset DataFrame index to prevent KeyError 

---

bots/models/bot_integration.py
widgets/demo_button.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

add SMS link for twilio demo

---

widgets/workflow_search.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

add close button to search box

---

daras_ai_v2/base.py
recipes/BulkEval.py
recipes/BulkRunner.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

refactor: remove split_output_tab

---

routers/workspace.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix: text changes on workspace creation / invitation flow

---

daras_ai_v2/text_splitter.py

- **add claude 4 sonnet & claude 4 opus**
- **use openai SDK for claude 4 models - support function calling**
- **fix: token counting for claude LLMs with openai-sdk**
```bash
```
```bash
```
```bash
```
```bash
```
To reduce import times, import libraries that take a long time inside the functions that use them instead of at the top …

fix: cost logging for claude models

---

widgets/saved_workflow.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

feat: show demo pill in saved workflow list

---

daras_ai_v2/language_model.py
daras_ai_v2/text_splitter.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

rollback using openai sdk for claude 4 models

---

daras_ai_v2/language_model.py

<details>
<p>
```bash
```
```bash
```
```bash
```
```python
...
```
</p>
</details> …

deprecate gpt4.5, with redirect to gpt 4o for existing runs

---

daras_ai_v2/paypal.py

<details>
<p>
```bash
```
```bash
```
```bash
```
```python
...
```
</p>
</details> …

fix: subscriptions with paypal

---

daras_ai_v2/base.py
daras_ai_v2/query_params_util.py
daras_ai_v2/workflow_url_input.py
routers/root.py

Currently, clicking on a version from a published-run page takes you to the individual saved-run page. The URL is like `https://gooey.ai/copilot/published-run-slug-pr_id_123/?run_id=...&uid=...`, so we can fetch the active published-run from the URL if it is there. This way, the flow of `{icon.save} Update` -> `{icon.save} Save` can be used to update the same published run.
It is not entirely consistent because versions can also contain updates to visibility settings or title/description. These changes are not rolled back with only the saved run. This can be fixed by changing the links and adding a param for the version ID, e.g. a URL such as `https://gooey.ai/copilot/published-run-slug-pr_id_123/version_id_123_here`.
---
- **refactor: stricter typing for extract_query_params**
- **feat: …

feat: better version-restore logic by preferring to fetch pr from URL

---

routers/root.py

1. in mobile view, go to workflow page e.g. copilot root
2. press "{magnifying-glass}" search icon
3. now resize to more than 768px width 
<details>
<p>
```bash
```
```bash
```
```bash
```
```python …
```

fix: remove ui state when header icons are hidden after resizing

---

widgets/workflow_search.py

<details>
<p>
```bash
```
```bash
```
```bash
```
```python
...
```
</p>
</details> …

fix: filter dropdowns overflow in width

---

daras_ai_v2/stable_diffusion.py

<details>
<p>
```bash
```
```bash
```
```bash
```
```python
...
```
</p>
</details> …

fix: raise UserError when text_prompt is missing for flux & gpt_image_1

---

widgets/workflow_share.py

earlier: only shown to workflow creator, workspace admins, and gooey admins
<details>
<p>
```bash
```
```bash
```
```bash
```
```python
...
```
</p>
</details> …

fix: show public access to all workspace members

---

daras_ai_v2/language_model.py

Earlier, streaming was disabled because the Azure OpenAI
API did not support it with the o1 model. That is no longer
the case.
<details>
<p>
```bash
```
```bash
```
```bash
```
```python
def …
```

fix: o1 now supports streaming from the azure API

---

daras_ai_v2/asr.py

<details>
<p>
```bash
```
```bash
```
```bash
```
```python
...
```
</p>
</details> …

feat: add support for akera ASR model

---

daras_ai_v2/settings.py
routers/root.py
workspaces/widgets.py

<details>
<p>
```bash
```
```bash
```
```bash
```
```python
...
```
</p>
</details> …

feat: add explore link in header

---

daras_ai_v2/language_model.py

<details>
<p>
```bash
```
```bash
```
```bash
```
```python
...
```
</p>
</details> …

fix: support image input with sealion v4
