GooeyAI/gooey-server

recipes/VideoBotsStats.py

Task: https://app.asana.com/0/1203067047205953/1205803182949984
```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

Allow free users to access the analytics page

---

gooey_ui/components/__init__.py
recipes/Functions.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

Code editor in Functions

---

handles/models.py

- Disable /js/ handle
- Disallow handles that might conflict with common asset routes
```bash
```
```bash
```
```bash
```
```bash
```
```python
...
```
Look, I get …

Disallow handles that conflict with common asset paths

---

daras_ai_v2/bot_integration_widgets.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

replace enableVideoLipsync with autoPlayResponses

---

recipes/FaceInpainting.py
recipes/Img2Img.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

Add safety checker for face inpainting recipe

---

daras_ai_v2/base.py

Co-related PR - https://github.com/GooeyAI/gooey-gui/pull/38
```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

Fix z-index issue for Sticky Submit bar

---

recipes/VideoBots.py

Task: https://app.asana.com/0/1203067047205953/1205803182950204
```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

Remove Open Messenger link

---

templates/payment_setup.html

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix trailing slash in paypal webhook route

---

routers/root.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix: tab icon alignment on webkit browsers

---

daras_ai_v2/billing.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

Fix: credit count in upgrade message & update messages for clarity

---

tests/test_translation.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix google translate test

---

daras_ai_v2/billing.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix subscription upgrade on indian cards: cancel & create new subscription on failure

---

daras_ai_v2/bot_integration_widgets.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

add enableConversations config

---

recipes/VideoBots.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix: integrations dropdown overflow in mobile

---

daras_ai_v2/asr.py
daras_ai_v2/text_to_speech_settings_widgets.py
recipes/TextToSpeech.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

Add GHANA NLP TTS API v1

---

daras_ai_v2/asr.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

use the correct language set for chirp asr model

---

daras_ai_v2/base.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix: render new price if request changed

---

daras_ai_v2/asr.py
recipes/Translation.py
recipes/VideoBots.py
recipes/asr_page.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

Asr built in translation

---

daras_ai_v2/asr.py
recipes/VideoBots.py
recipes/asr_page.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

Built in Translation Bugs

---

poetry.lock
pyproject.toml

- upgrade mediapipe from 0.9.2 to 0.10.18
- remove mediapipe-silicon (official mediapipe supports arm64 since 0.9.3)
- running face inpainting recipe on apple silicon
```bash
```
```bash
```
```bash
```
```bash
```
To reduce import times, import libraries that take a long time inside the functions that use them instead of at the top of …

fix mediapipe version: upgrade to 0.10.18

---

functions/recipe_functions.py
poetry.lock
pyproject.toml
recipes/VideoBots.py

Corresponding UI PR - https://github.com/GooeyAI/gooey-gui/pull/44
```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

replace checkbox with switch component

---

daras_ai_v2/settings.py
routers/root.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

UI: add rect logo for mobile

---

daras_ai_v2/profiles.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

remove signout from profiles page

---

templates/workspace_invitation_email.html
workspaces/tasks.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix invitation email

---

daras_ai_v2/base.py

- **fix another case where linkto could be None**
- **fix case in breadcrumb where linkto was None - when user.handle is None**
```bash
```
```bash
```
```bash
```
```bash
```
```python …
```

fix: bug in rendering workspace>author breadcrumb where author.handle is None

---

daras_ai_v2/settings.py
templates/auto_added_to_workspace_email.html
workspaces/models.py
workspaces/signals.py
workspaces/tasks.py

- **remove feature to auto-add members with matching domain name without invitation**
- **update email text for auto accepted email**
```bash
```
```bash
```
```bash
```
```bash
```
```python
def …
```

update text for auto-added to workspace email

---

templates/auto_added_to_workspace_email.html
templates/workspace_invitation_email.html

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix: invite link in invitation email and small text improvements

---

daras_ai_v2/analysis_results.py
daras_ai_v2/copy_to_clipboard_button_widget.py
daras_ai_v2/icons.py
daras_ai_v2/manage_api_keys_widget.py
recipes/VideoBots.py

- **update icon after copy link button is finished**
- **don't resize copy-link button when updating text if it is already big enough**
- **use icons.check instead of full fontawesome tag for copy-link button in analytics view**
```bash
```
```bash
```
```bash
```
```bash
```
To reduce import times, import libraries that take a long …

Fix copy-link button

---

daras_ai_v2/settings.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

add security settings for django admin dashboard

---

bots/models.py
daras_ai_v2/base.py
daras_ai_v2/urls.py
routers/account.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

Add pagination for published run pages

---

daras_ai_v2/base.py
recipes/TextToSpeech.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

remove visibility filter on /examples

---

workspaces/signals.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

bugfix: only invite new users to workspaces with matching domain, accept all pending invitations on AppUser->post_save

---

workspaces/widgets.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

workspace selector: update text 'manage workspace'->'open workspace' for non-admins

---

workspaces/signals.py

This reverts commit 290ad5aa8a9ee2c0a87fb4f5a24a66e0647089db, reversing
changes made to bce24d50fd9fbcf3e3bb5a50c059ce7560618fd8.
```bash
```
```bash
```
```bash
```
```bash
```
```python
def …
```

Revert "Merge pull request #536 from GooeyAI/workspace-signal-bug"

---

workspaces/signals.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix usage of create_and_send_invite, only handle ValidationError

---

workspaces/admin.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

add description field to workspace-admin

---

daras_ai_v2/bots.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

gracefully handle missing savedrun for bot integration

---

app_users/models.py
scripts/fix_email_or_phone_number_is_str_None.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix: phone number / email is being set to `'None'` for new users

---

daras_ai_v2/base.py
functions/recipe_functions.py
recipes/VideoBots.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

refactor & split tool construction, bind() and __call__

---

daras_ai/text_format.py
daras_ai_v2/meta_content.py
daras_ai_v2/tts_markdown_renderer.py
recipes/TextToSpeech.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

add workspace name to title meta tag

---

templates/auto_added_to_workspace_email.html

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix email text for welcome to {workspace} email

---

daras_ai_v2/base.py
daras_ai_v2/text_to_speech_settings_widgets.py
functions/models.py
functions/recipe_functions.py
managed_secrets/models.py
managed_secrets/signals.py
managed_secrets/widgets.py
recipes/Functions.py
recipes/TextToSpeech.py
recipes/VideoBots.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix array type argument in tools

---

daras_ai_v2/language_model.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

add 25K to max tokens chosen by user for o1 models

---

daras_ai_v2/doc_search_settings_widgets.py
recipes/VideoBots.py
tests/test_translation.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

update title icons videobots

---

daras_ai_v2/vector_search.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix duplicate reference

---

daras_ai_v2/serp_search_locations.py
functions/recipe_functions.py
recipes/GoogleGPT.py

allow disabling deep search and generate answer on google gpt
```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

allow calling any recipe via functions

---

bots/tasks.py
daras_ai_v2/workflow_url_input.py
recipes/VideoBotsStats.py

- **preserve existing variables on scheduled run**
- **add link to functions history page for scheduled export functions**
```bash
```
```bash
```
```bash
```
```bash
```
```python …
```

Scheduled run improvements

---

daras_ai_v2/language_model.py
scripts/init_llm_pricing.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

add o1 and o3-mini models

---

scripts/run-tests.sh
tests/test_integrations_api.py

checking if tests pass
```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

add new fixture link

---

daras_ai_v2/language_model.py
scripts/init_llm_pricing.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

add gemini 2 flash

---

daras_ai_v2/language_model.py
scripts/init_llm_pricing.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

add azure openai LLMs

---

bots/models.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

Fix text and options in share dialog

---

bots/models.py
recipes/VideoBotsStats.py

- **add Message ID and Conversation ID to copilot analytics (Messages view)**
- **add saved_copilot_url and integration_id to copilot analytics export fn args**
```bash
```
```bash
```
```bash
```
```bash
```
To reduce import times, import libraries that take a long time inside the functions that use them instead of at the top of the …

add fields to copilot analytics export

---

daras_ai_v2/bots.py
daras_ai_v2/facebook_bots.py
scripts/test_wa_msg_send.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

Refactor parse_bot_html to enable gui-action "disable_feedback"

---

bots/models.py
bots/tests.py
celeryapp/celeryconfig.py
recipes/VideoBotsStats.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

add assistant message on same row as user message in copilot analytics messages export

---

daras_ai_v2/asr.py
daras_ai_v2/settings.py

The vulavula SDK is not used becuase it relied on their own deprecated endpoint.
It also doesn't allow audio files to be passed from memory (they take a file path
as an argument).
```bash
```
```bash
```
```bash
```
```bash
```
To reduce import times, import libraries that take a long time inside the functions that use them instead of …

add Lelapa AI support for ASR & MT

---

daras_ai_v2/language_model.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

remove capping of gemini max_output_tokens to 1024 tokens

---

payments/plans.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

update contact_us_link to use CONTACT_URL instead of SALES_EMAIL

---

daras_ai_v2/asr.py
daras_ai_v2/language_model.py
daras_ai_v2/stable_diffusion.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

deprecate less frequently used models

---

.github/workflows/gitleaks.yml

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

gitleaks: update NOTIFY_USER_LIST to current team

---

widgets/author.py
widgets/saved_workflow.py
widgets/workflow_search.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

Saved workflow author fix

---

daras_ai_v2/language_model.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

increase gemini 2.5 max_output_tokens lower bound to 25,000

---

daras_ai_v2/realtime_llm_openai.py
routers/twilio_ws_api.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

feat: add gui-action for Twilio  transfer_call  in realtime LLM

---

daras_ai_v2/meta_content.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

meta image: prefer pr.photo_url for published runs

---

daras_ai_v2/language_model.py
scripts/init_llm_pricing.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

add function calling support for gemini models (from openai API)

---

widgets/demo_button.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix: download button in qr demo should download qr image

---

daras_ai_v2/language_model.py
scripts/init_llm_pricing.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

add claude 4 sonnet & claude 4 opus

---

daras_ai_v2/bot_integration_widgets.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

Fix integration company field

---

daras_ai_v2/base.py
widgets/saved_workflow.py
widgets/workflow_metadata_gen.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

add border-radius: 12px to workflow images

---

widgets/demo_button.py
widgets/saved_workflow.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

show colored demo pill

---

daras_ai_v2/base.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix: overflow content in tabs & demo button align

---

daras_ai_v2/settings.py
routers/root.py
server.py
templates/base.html
templates/header.html
workspaces/widgets.py

```bash
```
```bash
```
```bash
```
```bash
```
```python
...
``` …

fix: icon loading on 404 page

---

daras_ai_v2/language_model.py
daras_ai_v2/text_splitter.py

- **Revert "rollback using openai sdk for claude 4 models"**
- **fix claude to work with openai sdk: iter over response.__stream__() and not response**
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1210496356500391

fix claude 4

---

daras_ai_v2/bot_integration_widgets.py
recipes/VideoBots.py

<details>
<p>
```bash
```
```bash
```
```bash
```
```python
...
```
</p>
</details> …

Web widget preview sources checkbox 

---

functions/recipe_functions.py

…nvocation in call_recipe_functions
<details>
<p>
```bash
```
```bash
```
```bash
```
```python
...
```
</p>
</details> …

set default argument for WorkflowLLMTool

---

daras_ai_v2/bot_integration_widgets.py

<details>
<p>
```bash
```
```bash
```
```bash
```
```python
...
```
</p>
</details> …

fix: render twilio_specific uploaded files

---

daras_ai_v2/language_model_openai_realtime.py
recipes/VideoBots.py

<details>
<p>
```bash
```
```bash
```
```bash
```
```python
...
```
</p>
</details> …

feat: improve transcript for realtime audio

---

recipes/VideoBots.py

<details>
<p>
```bash
```
```bash
```
```bash
```
```python
...
```
</p>
</details> …

correct default on falsy values - realtime audio history

---

widgets/workflow_search.py

to make keyboard disappear
<details>
<p>
```bash
```
```bash
```
```bash
```
```python
...
```
</p>
</details>
Look, I get it. The entity doing business as …

fix: blur search bar on pressing enter

---

bots/models/saved_run.py
daras_ai_v2/base.py
daras_ai_v2/breadcrumbs.py
daras_ai_v2/chat_explore.py
daras_ai_v2/meta_content.py
daras_ai_v2/workflow_url_input.py
functions/recipe_functions.py
recipes/BulkRunner.py
recipes/VideoBots.py
widgets/base_header.py
widgets/demo_button.py
widgets/saved_workflow.py

<details>
<p>
```bash
```
```bash
```
```bash
```
```python
...
```
</p>
</details> …

Header layout changes

---

daras_ai_v2/base.py

<details>
<p>
```bash
```
```bash
```
```bash
```
```python
...
```
</p>
</details> …

fix margins for header title

---

bots/models/convo_msg.py

<details>
<p>
```bash
```
```bash
```
```bash
```
```python
...
```
</p>
</details> …

Show credits used and add integration name in csv

---

daras_ai_v2/asr.py

<details>
<p>
```bash
```
```bash
```
```bash
```
```python
...
```
</p>
</details> …

feat: add sunbird ugandan whisper & jacaranda health swahili to ASR models

---

daras_ai_v2/language_model.py

<details>
<p>
```bash
```
```bash
```
```bash
```
```python
...
```
</p>
</details> …

fix: update labels for GPT-5 models

---

recipes/VideoBots.py

<details>
<p>
```bash
```
```bash
```
```bash
```
```python
...
```
</p>
</details> …

fix: typo exracted->extracted

---

daras_ai_v2/language_model.py
daras_ai_v2/settings.py

<details>
<p>
```bash
```
```bash
```
```bash
```
```python
...
```
</p>
</details> …

refactor: remove commented references to together-ai API

---

daras_ai_v2/language_model.py

- **refactor: remove commented LLMApis.together**
- **feat: add claude 4.1 opus support**
<details>
<p>
```bash
```
```bash
```
```bash
```
```python
...
``` …

feat: add support for claude 4.1 opus

---

scripts/init_llm_pricing.py

<details>
<p>
```bash
```
```bash
```
```bash
```
```python
...
```
</p>
</details> …

fix: add pricing for claude 4.1 opus

---

workspaces/widgets.py

<details>
<p>
```bash
```
```bash
```
```bash
```
```python
...
```
</p>
</details> …

fix: padding on workspace dropdown buttons

---

daras_ai_v2/language_model.py
scripts/init_llm_pricing.py

<details>
<p>
```bash
```
```bash
```
```bash
```
```python
...
```
</p>
</details> …

feat: add gemini 2.5 flash lite

---

daras_ai_v2/asr.py

<details>
<p>
```bash
```
```bash
```
```bash
```
```python
...
```
</p>
</details> …

feat: add mbaza asr model

---

daras_ai_v2/base.py

<details>
<p>
```bash
```
```bash
```
```bash
```
```python
...
```
</p>
</details> …

fix: show preview tab on md view port

---

daras_ai_v2/base.py

<details>
<p>
```bash
```
```bash
```
```bash
```
```python
...
```
</p>
</details> …

fix: show flag and timestamp in preview tab

---

recipes/VideoBots.py

<details>
<p>
```bash
```
```bash
```
```bash
```
```python
...
```
</p>
</details> …

fix: hide lipsync options when lipsync switch is disabled

---

widgets/workflow_search.py

<details>
<p>
```bash
```
```bash
```
```bash
```
```python
...
```
</p>
</details> …

fix: remove rank from order_by when search is empty

---

daras_ai_v2/language_model.py

<details>
<p>
```bash
```
```bash
```
```bash
```
```python
...
```
</p>
</details> …

fix: image input creates invalid API request for apertus model
